config/routes.rb
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.has_role? :super_admin } do
    require 'sidekiq/web'
    Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_token]
    Sidekiq::Web.set :sessions, Rails.application.config.session_options
    mount Sidekiq::Web => '/sidekiq'
  end

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'categories#index'

  resources :categories, only: [:index, :show] do
    resources :brands, only: :index, controller: 'categories/brands'
  end
  resources :products, only: :show
  resources :pages, only: :show
  resources :cart, only: :index
  resources :sitemap, only: :index
  resources :yandex_market, only: :index
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, only: [:edit, :update] do
    resources :confirmation, controller: 'orders/confirmation'
  end
  resources :contacts, only: :index

  namespace :delivery do
    resources :sdek do
      get :autocomplete, on: :collection
    end
  end

  namespace :payments do
    resources :yandex_kassa do
      post :check, on: :collection
      post :aviso, on: :collection
      get :success, on: :collection
    end
  end

  namespace :market do
    resources :products
    resources :own_products
    resources :categories
  end

end

app/models/category/market.rb
class Category::Market < Category

  class << self

    def for_menu
      includes(:products)
        .where(parent_id: 0, published: true)
        .where(products: { aasm_state: 'published', is_valid: true, type: ['Product::Market'] })
        .order(:name)
    end

    def cache_name_categories_tree_hash
      'store_categories_tree_hash_market'
    end

    def cache_name_categories_tree_view
      'web_shop_categories_tree_view_market'
    end

    def tree_hash
      Rails.cache.fetch(cache_name_categories_tree_hash, expires_in: 1.day) do
        tree_hash = {}
        Category::Market.for_menu.each do |category|
          tree_hash[category.id] = {}
          tree_hash[category.id][:name] = category.name
          tree_hash[category.id][:human_name] = category.human_name
          tree_hash[category.id][:slug] = category.slug
          tree_hash[category.id][:parent_id] = category.parent_id
          tree_hash[category.id][:link] = category_path(category)
        end
        tree_hash
      end
    end

    def clear_cache
      Rails.cache.delete(cache_name_categories_tree_hash)
      Rails.cache.delete(cache_name_categories_tree_view)
    end

  end

end

app/models/product.rb
class Product < ApplicationRecord
  include AASM
  
  has_paper_trail class_name: 'ProductVersion'

  validates :name, presence: true
  validates :price, presence: true
  validates :category_id, presence: true

  has_many :product_images, dependent: :destroy
  has_many :field_values, dependent: :destroy
  has_many :fields, through: :field_values
  has_many :reviews
  belongs_to :category
  belongs_to :brand
  belongs_to :source_product, dependent: :destroy

  scope :initialized, -> { where(aasm_state: 'initialized') }
  scope :moderation, -> { where(aasm_state: 'moderation') }
  scope :published, -> { joins(:category).where(aasm_state: 'published', is_valid: true, categories: { published: true }).where('products.quantity > ?', 0) }
  scope :rejected, -> { where(aasm_state: 'rejected') }
  scope :ready_to_show, -> { published.includes(:product_images, :brand).references(:product_images, :brand) }
  scope :without_source_product, -> { includes(:source_product).where(source_products: { id: nil }) }
  scope :with_source_product, -> { joins(:source_product) }
  scope :special_offer, -> { where(special_offer: true) }

  scope :moderated_price, -> { joins(:source_product).where(aasm_state: 'moderation').where("products.price > source_products.price") }

  after_commit :delete_view_cache, on: [:update, :destroy]
  before_save :check_availability!
  before_save :set_min_price

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  accepts_nested_attributes_for :product_images, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :field_values, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reviews, reject_if: :all_blank, allow_destroy: true

  MIN_COMMISSION_COEFF = 0.35

  class << self
    include Rails.application.routes.url_helpers
    
    def yandex_market_arr
      Rails.cache.fetch('yandex_market_products_arr', expires_in: 1.day) do
        res = []
        Product.ready_to_show.where.not(brand_id: nil).find_each do |product|
          res << {
            id: product.id, 
            brand_name: product.brand.name,
            name: product.name,
            url: product_url(product[:id], host: 'fisher-secrets.ru', protocol: 'https', port: nil),
            price: product.price.to_i,
            category_id: product.category_id,
            picture_url: "https://#{@host}#{product.main_image.file.medium.url}",
            description: product.description,
            min_order: product.min_order
          }
        end
        res
      end
    end

  end

  aasm do
    state :initialized, initial: true
    state :moderation, :published, :rejected

    event :to_moderate do
      transitions to: :moderation
    end

    event :publish do
      transitions from: :moderation, to: :published, if: :can_be_published?
    end

    event :reject do
      transitions to: :rejected
    end

  end

  def source_price
    source_product.try(:price).to_f
  end

  def discount_price(user)
    extra_percents = 15
    if user.try(:spinning36) && source_product.present?
      extra = source_price/100.0 * extra_percents
      source_price + extra
    else
      nil
    end
  end

  def real_price(user)
    discount_price(user) || price
  end

  def can_be_published?
    has_images = product_images.where(product_images: { main: true }).any?
    source_price_cond = if source_product.present?
      price > source_price
    else
      true
    end
    quantity > 0 && price.nonzero? && source_price_cond && has_images
  end
  
  def cache_name_for_short_view
    "short_product_info_#{ id }"
  end
  
  def cache_name_for_full_view
    "full_product_info_#{ id }"
  end

  def delete_view_cache
    Rails.cache.delete(cache_name_for_short_view)
    Rails.cache.delete(cache_name_for_full_view)
  end

  def main_image
    product_images.first
  end

  def full_name
    "#{brand.try(:name)} #{name}"
  end

  def can_be_sale?
    Product.published.pluck(:id).include?(id)
  end

  def check_availability!
    if quantity < 1 && aasm_state != 'rejected'
      reject
    end
  end

  def set_min_price!
    set_min_price
    save!
  end

  protected

  def set_min_price
    self.min_price = price * min_order
  end

end

app/models/product/market.rb
class Product::Market < Product

  belongs_to :user
  validates :user_id, presence: true

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

app/models/product/piranya.rb
class Product::Piranya < Product

  validate :valid_price_value?

  before_save :set_price_margin
  before_save :set_retail_price_margin

  scope :for_autopublish, -> { moderation.joins(:source_product).where('min_order = 1') }

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  class << self

    def autocorrect!(force=false)
      joins(:brand).where(autocorrected: (false|force)).find_each(&:autocorrect!)
    end

    def autopublish!
      for_autopublish.find_each do |p|
        p.autopublish!
      end
    end

  end

  def autocorrect!
    name_rule = brand.name.gsub('ё', 'е')
    new_name = name
                .gsub('ё', 'е')
                .gsub(/#{name_rule}/i, '')
                .gsub('  ', ' ')
    description_rule = '<img width="\d+" src="(\S)*" height="\d+" border="\d+" hspace="\d+">'
    new_description = description.gsub(/#{description_rule}/i, '')
    self.update_attributes(name: new_name, description: new_description, autocorrected: true)
  end

  def autopublish!
    set_autopublish_price
    save! #TODO try to do it just with publish! method
    if can_be_published?
      publish!
    else
      update_from_source
      can_be_published? ? publish! : reject!
    end
  end

  def set_autopublish_price
    # logick uses piranya prices
    #  if retail_price.to_f.nonzero? && retail_price > source_product.price
    #    self.price = retail_price
    #  end
    #with retail_price
    price_with_coeff = (source_product.price + (source_product.price * MIN_COMMISSION_COEFF))
    self.price = if retail_price.to_f.nonzero? && (retail_price.to_f < price_with_coeff)
      retail_price
    else
      price_with_coeff
    end
  end

  def set_price_margin
    if source_price.to_f.nonzero? && price.to_f.nonzero?
      self.price_margin = price/(source_price.to_f/100)-100
    end
  end

  def set_retail_price_margin
    if source_price.to_f.nonzero? && retail_price.to_f.nonzero?
      self.retail_price_margin = retail_price/(source_price.to_f/100)-100
    end
  end

  def update_from_source_product
    if published?
      Rails.logger.info('Product must be unpublished for update from source_product')
      false
    else
      update_attributes(source_product.attributes_for_product)
    end
  end

  def update_from_source
    source_product.update_from_source
    update_from_source_product
  end

  protected

  def valid_price_value?
    source_price < price.to_f
  end

end

app/models/product/search.rb
class Product::Search

  DEFAULT_SOURCE_COLLECTION = ->{ Product.all }

  def self.build(params, source_collection=DEFAULT_SOURCE_COLLECTION)
    new(params, source_collection).build
  end
  
  def initialize(params={}, source_collection=DEFAULT_SOURCE_COLLECTION)
    @params = {}
    # standartize params. Keys is always Symbols, values is a String.
    params.each do |k, v|
      @params[k.to_sym] = v.to_s
    end
    @collection = source_collection
  end

  def build
    prepare_collection
    filter_by_category
    filter_by_brand
    filter_by_price
    @collection
  end

  protected

  def filter_by_category
    if @params[:category_id].present?
      @collection = @collection.where(category_id: @params[:category_id].to_i)
    end
    if @params[:category].present?
      category_id = Category.find_by_friendly_id_slug(@params[:category]).try(:id)
      @collection = @collection.where(category_id: category_id) if category_id
    end
  end

  def filter_by_brand
    if @params[:brand_id].present?
      @collection = @collection.where(brand_id: @params[:brand_id].to_i)
    end
    if @params[:brand].present?
      brand_id = Brand.find_by_friendly_id_slug(@params[:brand]).try(:id)
      @collection = @collection.where(brand_id: brand_id) if brand_id
    end
  end

  def filter_by_price
    if @params[:min_price].present?
      @collection = @collection.where('price >= ?', @params[:min_price].to_f)
    end
    if @params[:max_price].present?
      @collection = @collection.where('price <= ?', @params[:max_price].to_f)
    end
  end

  def prepare_collection
    @collection = @collection.call if @collection.is_a?(Proc)
  end

end

app/controllers/market/categories_controller.rb
class Market::CategoriesController < CategoriesController
  include MarketCommon

  private

  def index_products_collection
    Product::Market.published
  end

  def category_products(category)
    category.market_products
  end

end

app/controllers/market/own_products_controller.rb
class Market::OwnProductsController < ApplicationController
  include MarketCommon
  layout 'application'
  load_and_authorize_resource class: 'Product::Market'

  def index
    @products = Product::Market.where(user_id: current_user)
  end

  def publish
    @product.publish!
  end

  def to_modetarion
    @product.to_moderation!
  end

end

app/controllers/market/products_controller.rb
class Market::ProductsController < ProductsController
  #load_and_authorize_resource :product
  load_and_authorize_resource
  include MarketCommon

  def new
    @product = Product::Market.new
    @product.product_images.build(main: true)
  end

  def create
    @product = MarketProductServiceObject.create(
      product_params,
      current_user
    )
    if @product.persisted?
      @product.to_moderate!
      @product.publish!
      Category::Market.clear_cache
      redirect_to(market_categories_path)
    else
      @product.product_images.build(main: true)
      render :new
    end
  end

  private

  def product_params
    params.require(:product_market).permit(:name,  :category_id, :description, :price, product_images_attributes: [:file])
  end

  def product_classes
    ['Product::Market']
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  include WebshopCommon

  def show
    @product = Product.where(type: product_classes)
                      .includes(:category, :product_images, field_values: :field)
                      .find(params[:id])
    @category = @product.category
    @brand = @product.brand
    @website_breadcrumbs << { name: @product.category.human_name, url: category_path(@product.category) }
    @current_page_title = { name: @product.category.human_name, url: category_path(@product.category)}
    prefix = @product.category.product_prefix
    prefix += " " unless prefix.blank?
    @website_title = "#{prefix}#{@product.full_name}. В интернет-магазине Fisher-Secrets"
  end

  private

  def product_classes
    ['Product::Piranya', 'Product', nil]
  end

end

app/views/market/products/new.slim
h2 Добавление товара
br

- @product.errors.full_messages.each do |message|
  = content_tag :div, message, class: "alert alert-danger"

= form_for @product, url: market_products_path, method: :post, html: { id: 'add_product_to_market' } do |f|
  .form_group
    = f.label :name, 'Название'
    = f.text_field :name, autofocus: true, class: 'form-control'
  .form_group
    = f.label :category_id, 'Категория'
    = f.select :category_id, Category.array_for_select, {}, class: 'form-control'
  .form_group
    = f.label :description, 'Описание'
    = f.text_area :description, class: 'form-control'
  .form_group
    = f.label :price, 'Цена (руб.)'
    = f.number_field :price, class: 'form-control'
  = f.fields_for :product_images do |image_field|
    .form_group
      = image_field.label :file, 'Изображение'
      = image_field.file_field :file
  br
  .actions
    = f.submit "Добавить", class: 'btn btn-primary'

app/views/market/products/show.html.haml
%section#market_product.mainContent.clearfix{ itemscope: true, itemtype: "http://schema.org/Product"}
  .container
    .row.singleProduct
      .col-xs-12.col-md-9
        .media
          .media-left.productSlider
            #carousel.carousel.slide{ :'data-ride' => 'carousel' }
              .carousel-inner
                - @product.product_images.each_with_index do |image, index|
                  %div{ :'data-thumb' => index, class: "item#{ index.zero? ? ' active' : '' }" }
                    = image_tag image.file.small, (index.zero? ? { itemprop: "image", alt: @product.full_name } : {})
            .clearfix
              #thumbcarousel.carousel.slide{ :'data-interval' => false }
                .carousel-inner
                  - @product.product_images.each_with_index do |image, index|
                    .thumb{ :'data-target' => '#carousel', :'data-slide-to' => index }
                      = image_tag image.file.thumb
                %a{ class: 'left carousel-control', href: '#thumbcarousel', role: 'button', :'data-slide' => 'prev' }
                  %span.glyphicon.glyphicon-chevron-left
                %a{ class: 'right carousel-control', href: '#thumbcarousel', role: 'button', :'data-slide' => 'next' }
                  %span.glyphicon.glyphicon-chevron-right
          .media-body
            %h2{ itemprop: 'name' }= @product.full_name
            .tabArea
              .tab-content
                #details.tab-pane.fade.in.active
                  %ul.list-unstyled
                    - @product.field_values.each do |field_value|
                      %li
                        %b
                          = field_value.field.name
                          \:
                        = field_value.value
            %p.description{ itemprop: 'description' }
              = raw(@product.description)
            - if ['published', 'rejected'].include?(@product.aasm_state)
              %h3{ itemprop: 'offers', itemscope: true, itemtype: 'http://schema.org/Offer' }
                - if @product.real_price(current_user) != @product.price
                  %span{ itemprop: 'price', style: 'font-size: 16px; text-decoration: line-through;' }= number_with_delimiter(@product.price.to_i)
                  %br
                  %span{ itemprop: 'price' }= number_with_delimiter(@product.real_price(current_user).to_i)
                - else
                  %span{ itemprop: 'price' }= number_with_delimiter(@product.real_price(current_user).to_i)
                %small{ itemprop: 'priceCurrency' } р.
          .clearfix
          .clearfix
            .vendor_info
              %h3 Продавец
              - unless @product.user.name.blank?
                %p= @product.user.name
              - unless @product.user.phone.blank?
                %p= @product.user.phone
              - unless @product.user.address.blank?
                %p= @product.user.address