config/routes.rb
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.has_role? :super_admin } do
    require 'sidekiq/web'
    Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_token]
    Sidekiq::Web.set :sessions, Rails.application.config.session_options
    mount Sidekiq::Web => '/sidekiq'
  end

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'categories#index'

  resources :categories, only: [:index, :show] do
    resources :brands, only: :index, controller: 'categories/brands'
  end
  resources :products, only: :show
  resources :pages, only: :show
  resources :cart, only: :index
  resources :sitemap, only: :index
  resources :yandex_market, only: :index
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, only: [:edit, :update] do
    resources :confirmation, controller: 'orders/confirmation'
  end
  resources :contacts, only: :index

  namespace :delivery do
    resources :sdek do
      get :autocomplete, on: :collection
    end
  end

  namespace :payments do
    resources :yandex_kassa do
      post :check, on: :collection
      post :aviso, on: :collection
      get :success, on: :collection
    end
  end

  namespace :market do
    resources :products
    resources :own_products
    resources :categories
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def index
  end
  
end

app/views/cart/index.html.slim
section#cart_section.mainContent.clearfix.cartListWrapper
  .container
    .row
      .col-xs-12
        .cartListInner
          form action="#"
            .table-responsive
              table.table
                thead
                  tr
                    th
                    th Название
                    th Количество
                    th Цена за 1 ед.
                tbody
                  - current_order.order_items.each do |order_item|
                    tr
                      td.col-xs-2
                        = link_to order_item_path(order_item.id), class: 'close', method: :DELETE
                          span aria-hidden=true
                            | &times;
                        span.cartImage
                          = image_tag order_item.product.main_image.file.thumb, width: '63px'
                      td.col-xs-4= order_item.name
                      td.col-xs-2= order_item.quantity
                      td.col-xs-2
                        = order_item.unit_price.to_i
                        small
                          |  р.
            .row.totalAmountArea
              .col-sm-4.col-sm-offset-8.col-xs-12
                ul.list-unstyled
                  li
                    | Итого
                    span.grandTotal
                      = current_order.products_price.to_i
                      small
                        |  р.
            .checkBtnArea
              - if current_order.persisted?
                = link_to edit_order_path(current_order.public_id), class: 'btn btn-primary btn-block' do
                  | Оформить
                  i.fa.fa-arrow-circle-right aria-hidden=true