config/routes.rb
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.has_role? :super_admin } do
    require 'sidekiq/web'
    Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_token]
    Sidekiq::Web.set :sessions, Rails.application.config.session_options
    mount Sidekiq::Web => '/sidekiq'
  end

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'categories#index'

  resources :categories, only: [:index, :show] do
    resources :brands, only: :index, controller: 'categories/brands'
  end
  resources :products, only: :show
  resources :pages, only: :show
  resources :cart, only: :index
  resources :sitemap, only: :index
  resources :yandex_market, only: :index
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, only: [:edit, :update] do
    resources :confirmation, controller: 'orders/confirmation'
  end
  resources :contacts, only: :index

  namespace :delivery do
    resources :sdek do
      get :autocomplete, on: :collection
    end
  end

  namespace :payments do
    resources :yandex_kassa do
      post :check, on: :collection
      post :aviso, on: :collection
      get :success, on: :collection
    end
  end

  namespace :market do
    resources :products
    resources :own_products
    resources :categories
  end

end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  has_many :order_items, dependent: :destroy
  has_one :payment
  belongs_to :user
  validates :browser_session_hash, presence: true
  validate :destination_id_rules
  validate :check_order_items
  before_save :set_shipping_price

  aasm do
    state :initialized, initial: true
    state :ready_to_pay, :paid, :delivering, :completed, :rejected

    event :to_ready_to_pay do
      transitions from: :initialized, to: :ready_to_pay, if: :can_make_order?
    end

    event :to_pay do
      transitions from: :ready_to_pay, to: :paid
      after do
        OrderMailer.complete_order_customer(self.id).deliver_later!
        OrderMailer.complete_order_vendor(self.id).deliver_later!
        decrement_products!
      end
    end

    event :to_delivering do
      transitions from: :paid, to: :delivering
    end

    event :to_complete do
      transitions from: [:paid, :delivering], to: :complete
    end

    event :reject do
      transitions from: [:paid, :ready_to_pay, :delivering], to: :rejected
    end

  end

  def products_price
    order_items.sum { |oi| oi.full_price }.to_f
  end

  def total_price
    products_price + shipping_price.to_f
  end

  def add_product(product_id, quantity=1)
    save! unless persisted? #save order sesion on click buy button
    order_item = OrderItem.create_with(quantity: 0).find_or_create_by!(order_id: id, product_id: product_id)
    order_item.increment_quantity(quantity)
    order_item.save!
    save!
  end

  def can_make_order?
    items_condition = (order_items.map { |oi| oi.is_it_full_valid? }.exclude?(false))
    items_condition && destination_id.present? && shipping_price.nonzero? && shipping_address.present?
  end

  def destination_name
    SdekDestination.find_by_id(destination_id).try(:full_name)
  end

  def customer_full_name
    "#{first_name} #{last_name}"
  end

  def decrement_products!
    order_items.each do |order_item|
      new_product_quantity = order_item.product.quantity - order_item.quantity
      order_item.product.update_attributes(quantity: new_product_quantity)
    end
  end

  protected

  def set_shipping_price
    if destination_id.present?
      self.shipping_price = Client::Sdek.new.calculate(destination_id, 506)
    end
  end

  def destination_id_rules
    if destination_id.present? && SdekDestination.all.map(&:sdek_id).exclude?(destination_id)
      errors.add(:quantity, "Wrong destination_id.")
    end
  end

  def check_order_items
    invalid_items = order_items.detect { |order_item| !order_item.valid? }
    self.errors.add(:product_quantity, 'Invalid product in order!') if invalid_items
  end

end

app/controllers/orders/confirmation_controller.rb
class Orders::ConfirmationController < ApplicationController
  authorize_resource class: 'Order'

  def new
    @order = Order.find_by(public_id: params[:order_id], aasm_state: 'initialized')
    @shop_id = Rails.application.secrets[:yandex_kassa][:shop_id]
    @scid = Rails.application.secrets[:yandex_kassa][:scid]
    @customer_number = current_user.try(:id).to_i
    unless @order.can_make_order?
      flash[:error] = 'Ошибка заказа, проверьте корректность данных.'
      redirect_to edit_order_path(params[:order_id])
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_resource find_by: :public_id
  authorize_resource

  def edit
    @current_page_title = { name: 'Оформление заказа', url: edit_order_path(@order.id) }
    @website_breadcrumbs << { name: 'Оформление заказа', url: edit_order_path(@order.id) }
    @order.user_id = current_user.try(:id)
    @order.save!
  end

  def update
    @order.update_attributes!(order_params)
    redirect_to new_order_confirmation_path(@order.public_id)
  end

  private

  def order_params
    params.require(:order).permit(:first_name, :last_name, :email, :phone_number, :city, :region, :destination_id, :shipping_address)
  end

end

app/views/orders/edit.html.slim
section.mainContent.clearfix.stepsWrapper
  .container
    .row
      .col-xs-12
        .innerWrapper.clearfix.stepsPage
          .row.progress-wizard style='border-bottom:0;'
            .col-xs-6.progress-wizard-step.complete
              .text-center.progress-wizard-stepnum Заполнение данных
              .progress
                .progress-bar
              span.progress-wizard-dot
            .col-xs-6.progress-wizard-step.disabled
              .text-center.progress-wizard-stepnum Подтверждение заказа и оплата
              .progress
                .progress-bar
              span.progress-wizard-dot

          = form_for @order, url: order_path(@order.public_id) do |f|
            .col-xs-12
              .page-header
                h4 Платежная информация

            .form-group.col-sm-6.col-xs-12
              = f.label :first_name, 'Имя'
              = f.text_field :first_name, class: 'form-control', autofocus: true

            .form-group.col-sm-6.col-xs-12
              = f.label :last_name, 'Фамилия'
              = f.text_field :last_name, class: 'form-control'

            .form-group.col-sm-6.col-xs-12
              = f.label :email, 'Email'
              = f.email_field :email, class: 'form-control'

            .form-group.col-sm-6.col-xs-12
              = f.label :phone_number, 'Телефон'
              = f.text_field :phone_number, class: 'form-control'

            .form-group.col-sm-6.col-xs-12
              = f.label :destination_name, 'Город'
              = f.text_field :destination_name, class: 'form-control'
              = f.hidden_field :destination_id

            .form-group.col-sm-6.col-xs-12
              = f.label :shipping_address do
                | Адрес
                span style='color: #777777;'
                  |  (улица, дом, квартира и.т.п.)
              = f.text_area :shipping_address, class: 'form-control'

            .col-xs-12
              .well.well-lg.clearfix
                ul.pager
                  li.next
                    = f.submit 'Далее', class: 'btn btn-primary'