config/routes.rb
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.has_role? :super_admin } do
    require 'sidekiq/web'
    Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_token]
    Sidekiq::Web.set :sessions, Rails.application.config.session_options
    mount Sidekiq::Web => '/sidekiq'
  end

  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'categories#index'

  resources :categories, only: [:index, :show] do
    resources :brands, only: :index, controller: 'categories/brands'
  end
  resources :products, only: :show
  resources :pages, only: :show
  resources :cart, only: :index
  resources :sitemap, only: :index
  resources :yandex_market, only: :index
  resources :order_items, only: [:create, :update, :destroy]
  resources :orders, only: [:edit, :update] do
    resources :confirmation, controller: 'orders/confirmation'
  end
  resources :contacts, only: :index

  namespace :delivery do
    resources :sdek do
      get :autocomplete, on: :collection
    end
  end

  namespace :payments do
    resources :yandex_kassa do
      post :check, on: :collection
      post :aviso, on: :collection
      get :success, on: :collection
    end
  end

  namespace :market do
    resources :products
    resources :own_products
    resources :categories
  end

end

app/views/layouts/_cart.html.slim
= link_to 'javascript:void(0)', class: 'dropdown-toggle', :'data-toggle' => 'dropdown'do
  i.fa.fa-shopping-cart
  = current_order.try(:products_price).to_i
  |  р.
- if current_order.present? && current_order.order_items.any?
  ul.dropdown-menu.dropdown-menu-right
    li Товары в корзине
    - current_order.order_items.each do |order_item|
      li
        = link_to product_path(order_item.product) do
          .media
            = image_tag order_item.product.main_image.file.thumb, class: 'media-left media-object', alt: 'cart-Image', style: 'width: 50px;'
            .media-body
              h5.media-heading
                = truncate(order_item.name, length: 21)
                br
                span
                = order_item.quantity
                |&nbsp;X&nbsp;
                = order_item.unit_price
    li
      .btn-group role='group' aria-label='...'
        = link_to 'Корзина', cart_index_path, class: 'btn btn-default order_button'
        = link_to 'Оформить', edit_order_path(current_order.public_id), class: 'btn btn-default order_button' if current_order.persisted?

app/views/layouts/_footer.html.slim
section.lightSection.clearfix
  .container
    .row
      .col-xs-12
        .owl-carousel.partnersLogoSlider
          - @footer_brands.each do |brand|
            .slide
              .partnersLogo.clearfix= image_tag brand.image.thumb, alt: brand.name
.footer.clearfix
  .container
    .row
      .col-sm-3.col-xs-12
        .footerLink
          h5 Контакты
          ul.list-unstyled
            li Телефон +7 (901) 092-85-68
            li= link_to 'support@fisher-secrets.ru', 'mailto:support@fisher-secrets.ru'
      .col-sm-4.col-xs-12
        p= link_to 'Политика конфиденциальности', '/privacy.pdf'
        p= link_to 'Пользовательское соглашение', '/terms.pdf'
.copyRight.clearfix
  .container
    .row
      .col-sm-7.col-xs-12
        p
          | &copy; 2017 Copyright FISHER-SECRETS
      .col-sm-5.col-xs-12
        - if false #for a feature
          ul.list-inline
            li
              = link_to '#' do 
                i.fa.fa-twitter
            li
              = link_to '#' do 
                i.fa.fa-facebook
            li
              = link_to '#' do 
                i.fa.fa-dribbble
            li
              = link_to '#' do 
                i.fa.fa-vimeo
            li
              = link_to '#' do 
                i.fa.fa-tumblr
= render '/shared/jivo_site'

app/views/layouts/_head.html.slim
meta charset='utf-8'
meta http-equiv='X-UA-Compatible' content='IE=edge'
link rel='shortcut icon' href="/favicon.ico" type='image/x-icon'
title= @website_title
meta name='keywords' content=@website_keywords
meta name='description' content=@website_description
= stylesheet_link_tag 'application', media: 'screen'
= javascript_include_tag 'application'
/[if lt IE 9]
  = javascript_include_tag 'html5shiv.min.js'
  = javascript_include_tag 'respond.min.js'
= csrf_meta_tags
= render '/layouts/yandex_metrica'

app/views/layouts/_header.html.slim
.header.clearfix
  .topBar
    .container
      .row
        .col-md-6.hidden-sm.hidden-xs
          - if false #for a feature
            ul.list-inline
              li
                = link_to '#' do
                  i.fa.fa-twitter
              li
                = link_to '#' do
                  i.fa.fa-facebook
              li
                = link_to '#' do
                  i.fa.fa-dribbble
              li
                = link_to '#' do
                  i.fa.fa-vimeo
              li
                = link_to '#' do
                  i.fa.fa-tumblr
        .col-md-6.col-xs-12
          ul.list-inline.pull-right.top-right
            li.account-login
              span
                - if user_signed_in?
                  = link_to 'Выход', destroy_user_session_path, method: :delete
                  span.separator |
                  = link_to 'Профиль', edit_user_registration_path
                  span.separator |
                  = link_to 'Мои товары', market_own_products_path
                - else
                  = link_to 'Вход', '#login', :'data-toggle' => 'modal'
                  small или
                  = link_to 'Регистрация', '#signup', :'data-toggle' => 'modal'
            li#short_cart.dropdown.cart-dropdown
              = render '/layouts/cart'
  nav.navbar.navbar-main.navbar-default role='navigation'
    .container
      .navbar-header
        button.navbar-toggle type='button' data-toggle='collapse' data-target='.navbar-ex1-collapse'
          span.sr-only Переключить навигацию
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to root_path, class: 'navbar-brand' do
          = image_tag 'logo.png', alt: 'fisher secrets'
        #top_phone_number.hidden-sm.hidden-xs
          |тел.: +7 (901) 092-85-68
      .collapse.navbar-collapse.navbar-ex1-collapse
        ul.nav.navbar-nav.navbar-right
          li
            = link_to 'Интернет-магазин', root_path
          li
            = link_to 'Маркет', market_categories_path
          li
            = link_to 'Доставка', page_path(Page.find_by(code: 'delivery'))
          li
            = link_to 'Контакты', contacts_path
section.lightSection.clearfix.pageHeader
  .container
    .row
      .col-xs-6
        .page-title
          h1= link_to @current_page_title[:name], @current_page_title[:url]
      .col-xs-6
        ol.breadcrumb.pull-right
          - @website_breadcrumbs.each_with_index do |breadcrumb, index|
            li class="#{ 'active' if @website_breadcrumbs.size == index+1 }" = link_to breadcrumb[:name].try(:html_safe), breadcrumb[:url]

app/views/layouts/_modal.html.haml
- cache 'page_modal', expires_in: 1.hour do
  #login.modal.fade.login-modal{ tabindex: '-1', role: 'dialog' }
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{ type: 'button', :'data-dismiss' => 'modal', :'aria-hidden' => 'true' } &times;
          %h3.modal-title Вход на сайт
        .modal-body
          = form_for :user, url: user_session_path, role: 'form' do |f|
            .form-group
              = f.label :email
              = f.email_field :email, class: 'form-control'
            .form-group
              = f.label :password, 'Пароль'
              = f.password_field :password, autocomplete: "off", class: 'form-control'
            .checkbox
              %label
                = f.check_box :remember_me
                Запомнить меня
            %button.btn.btn-primary.btn-block{ type: 'submit' } Войти
            = link_to "Забыли пароль?", new_user_password_path, class: 'btn btn-link btn-block'

  #signup.modal.fade.login-modal{ tabindex: '-1', role: 'dialog' }
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{ type: 'button', :'data-dismiss' => 'modal', :'aria-hidden' => true } &times;
          %h3.modal-title Регистрация на сайте
        .modal-body
          = form_for :user, url: user_registration_path do |f|
            .form-group
              = f.label :email
              = f.email_field :email, class: 'form-control'
            .form-group
              = f.label :password, 'Пароль'
              = f.password_field :password, autocomplete: "off", class: 'form-control'
            .form-group
              = f.label :password_confirmation, 'Подтверждение пароля'
              = f.password_field :password_confirmation, autocomplete: "off", class: 'form-control'
            %button.btn.btn-primary.btn-block{ type: 'submit' } Зарегистрироваться

app/views/layouts/application.html.slim
doctype html
html lang="ru"
  head
    = render '/layouts/head'
  body.body-wrapper
    .main-wrapper
      = render '/layouts/header'
      - flash.each do |key, value|
        = content_tag :div, value, class: "alert alert-danger"
      = yield
      = render '/layouts/footer'
    = render '/layouts/modal'

app/views/layouts/market.html.slim
doctype html
html lang="ru"
  head
    = render '/layouts/head'
  body.body-wrapper
    .main-wrapper
      = render '/layouts/header'
      - flash.each do |key, value|
        = content_tag :div, value, class: "alert alert-danger"
      section.mainContent.clearfix.productsContent
        .container
          .row
            .col-md-3.col-sm-4.col-xs-12.sideBar
              .panel.panel-default
                .panel-heading Категории
                .panel-body
                  .collapse.navbar-collapse.navbar-side-collapse
                    ul.nav.navbar-nav.side-nav
                      - @tree_hash.each do |cat_id, cat_opt|
                        li
                          - is_active_category = (@category.try(:id) == cat_id)
                          = link_to market_category_path(cat_opt[:slug]) do
                            = cat_opt[:human_name]
                            - i_active_class = (is_active_category ? 'fa-minus' : 'fa-plus')
                            i class="fa #{ i_active_class }"
            .col-md-9.col-sm-8.col-xs-12
              - if controller_name == 'categories'
                .row.filterArea
                  .col-xs-6
                    select#guiest_id1.select-drop name='guiest_id1'
                      - CategoriesController::SORT_TYPES.each do |type|
                        option value=type[:name] selected=(type[:name]==@sort_type) data-url=sorted_page_url(type[:name])
                          ==type[:human_name]
              .row
                = yield
      = render '/layouts/footer'
    = render '/layouts/modal'

app/views/layouts/shop.html.slim
doctype html
html lang="ru"
  head
    = render '/layouts/head'
  body.body-wrapper
    .main-wrapper
      = render '/layouts/header'
      - flash.each do |key, value|
        = content_tag :div, value, class: "alert alert-danger"
      section.mainContent.clearfix.productsContent.content-wrapper
        .container
          .row.content-wrapper
            .col-md-3.col-sm-4.col-xs-12.sideBar
              .panel.panel-default
                .panel-heading Категории
                .panel-body
                  .collapse.navbar-collapse.navbar-side-collapse
                    ul.nav.navbar-nav.side-nav
                      - @tree_hash.each do |cat_id, cat_opt|
                        li
                          - is_active_category = (@category.try(:id) == cat_id)
                          = link_to category_brands_path(cat_opt[:slug]) do
                            = cat_opt[:human_name]
                            - i_active_class = (is_active_category ? 'fa-minus' : 'fa-plus')
                            i class="fa #{ i_active_class }"
                          - ul_active_class = (is_active_category ? ' in' : '')
                          - if is_active_category
                            ul id=cat_opt[:slug] class="collapse collapseItem#{ ul_active_class }"
                              li class="#{ (@brand.nil? && is_active_category) ? 'active' : '' }"
                              - cat_opt[:brands].each do |brand|
                                li class="#{ (@brand.try(:id) == brand[:id] && is_active_category) ? 'active' : '' }"
                                  = link_to brand[:link] do
                                    i.fa.fa-caret-right aria-hidden=true
                                    = brand[:name]
            .col-md-9.col-sm-8.col-xs-12
              - if controller_name == 'categories'
                .row.filterArea
                  .col-xs-6
                    select#guiest_id1.select-drop name='guiest_id1'
                      - CategoriesController::SORT_TYPES.each do |type|
                        option value=type[:name] selected=(type[:name]==@sort_type) data-url=sorted_page_url(type[:name])
                          ==type[:human_name]
              - if @brand.present? && controller_name == 'categories'
                .row.brand
                  h3= @brand.name
                  .description= raw(@brand.description)
              .row
                = yield
      = render '/layouts/footer'
    = render '/layouts/modal'